version: '3.8'

services:
  flask-app:
    container_name: PriceLookup
    build:
      context: .  # Build the Dockerfile in the current directory
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    restart: always
    networks:
      - shared-network  # Use the shared external network

networks:
  shared-network:
    external: true  # Use an external network created manually
